### ISSUE TITLE
Ch4/8 Form is not adding video to database

### ISSUE THREAD

**Issue by Joeriksson** [talkpython/htmx-django-course#1]
I started with the code from lesson03. After coding along and adding a form to submit new videos, I noticed that no videos were added to the database. Doing a bit debugging, I realized that the form had errors since there was no value for categories posted.

After adding the following line to the form in category.html the form worked without errors:

`<input type="hidden" name="categories" value="{{ category.id }}">`

**Comment by cltrudeau** [comment]
Hi Joe,

The `Category` is a `ManyToManyField` and as such shouldn't be required for the form to work. The approach I took was to add the category after the form validates and saves, using the category passed in to the view. 

You can see this in the lesson04a_form version of the code in the `category` view

https://github.com/talkpython/htmx-django-course/blob/24c279c6eb429da8438b975cf7acdd5a5a09d2aa/code/lesson04a_form/VideoCollector/content/views.py#L28

Without seeing your code, I can't be sure, but I'm guessing you included "category" as one of the field choices in the `VideoForm`. It isn't needed:

```
VideoForm = forms.modelform_factory(Video, fields=["youtube_id", "title", "author", "view_count"])
```

If I haven't understood the issue, please feel free to open another one.
