### ISSUE TITLE
Image does not match title

### ISSUE THREAD

**Issue by plockaby** [talkpython/htmx-django-course#3]
The name of the course is "HTMX + Django" but the very big image at the very top of the repository README says "HTMX + Flask" which is slightly confusing at first glance.

This is the current image at the top of the README:
<img width="1264" alt="Screenshot 2024-08-07 at 10 44 22 PM" src="https://github.com/user-attachments/assets/ac84ddd1-1ff4-4acc-aeff-985399f7c5bb">

**Comment by mikeckennedy** [comment]
Thanks for catching that @plockaby :)
